[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "check-json"
priority = 0

[[repos.hooks]]
id = "check-toml"
priority = 0

[[repos.hooks]]
id = "check-yaml"
priority = 0

[[repos.hooks]]
id = "end-of-file-fixer"
priority = 0

[[repos.hooks]]
id = "trailing-whitespace"
priority = 0

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.4"

[[repos.hooks]]
id = "ruff-check"
priority = 1
args = ["--fix"]

[[repos.hooks]]
id = "ruff-format"
priority = 0

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ty"
priority = 1
name = "ty check"
entry = "uv run ty check"
pass_filenames = false
language = "system"

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.11"

[[repos.hooks]]
id = "actionlint-docker"
priority = 1

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"

[[repos.hooks]]
id = "name-tests-test"
priority = 0
args = ["--pytest-test-first"]

[[repos]]
repo = "https://github.com/tox-dev/pyproject-fmt"
rev = "v2.16.2"

[[repos.hooks]]
id = "pyproject-fmt"
priority = 0
